"""Typed board and pin-map configuration."""

from dara.peripheral.pinmap import (
    BoardConfig,
    BoardInfo,
    PinMapConfig,
    PinInfo,
    ADCInfo,
    SoftKeyInfo,
    GPIOInfo,
    I2CInfo,
    SPIInfo,
    UARTInfo,
    WDTInfo,
)


BOARD_CONFIG = BoardConfig(
    config_version=1,
    board=BoardInfo(
        id="cv184x-mainboard",
        name="cv184x-mainboard",
        description="cv184x-mainboard",
        platform="cvitek",
        board_version="0.0.1",
    ),
    pinmap=PinMapConfig(
        pins={
            "C4": PinInfo(
                name="CAM_MCLK0",
                reg_addr=50335744,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 2, 3),
                funcs=("CAM_MCLK0", "AUX1", "XGPIOA_0"),
            ),
            "C3": PinInfo(
                name="CAM_PD0",
                reg_addr=50335748,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 3, 4),
                funcs=("IIS1_MCLK", "XGPIOA_1", "CAM_HS0"),
            ),
            "E5": PinInfo(
                name="CAM_RST0",
                reg_addr=50335752,
                bit_offset=0,
                bit_width=3,
                func_regs=(3, 4, 6),
                funcs=("XGPIOA_2", "CAM_VS0", "IIC4_SCL"),
            ),
            "D3": PinInfo(
                name="CAM_MCLK1",
                reg_addr=50335756,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 2, 3, 4),
                funcs=("CAM_MCLK1", "AUX2", "XGPIOA_3", "CAM_HS0"),
            ),
            "E4": PinInfo(
                name="CAM_PD1",
                reg_addr=50335760,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 3, 4, 6),
                funcs=("IIS1_MCLK", "XGPIOA_4", "CAM_VS0", "IIC4_SDA"),
            ),
            "D4": PinInfo(
                name="IIC3_SCL",
                reg_addr=50335764,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 3),
                funcs=("IIC3_SCL", "XGPIOA_5"),
            ),
            "F4": PinInfo(
                name="IIC3_SDA",
                reg_addr=50335768,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 3),
                funcs=("IIC3_SDA", "XGPIOA_6"),
            ),
            "L1": PinInfo(
                name="SD0_CLK",
                reg_addr=50335772,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 5, 6, 7),
                funcs=(
                    "SDIO0_CLK",
                    "IIC1_SDA",
                    "SPI0_SCK",
                    "XGPIOA_7",
                    "PWM_15",
                    "EPHY_LNK_LED",
                    "DBG_0",
                ),
            ),
            "L3": PinInfo(
                name="SD0_CMD",
                reg_addr=50335776,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 5, 6, 7),
                funcs=(
                    "SDIO0_CMD",
                    "IIC1_SCL",
                    "SPI0_SDO",
                    "XGPIOA_8",
                    "PWM_14",
                    "EPHY_SPD_LED",
                    "DBG_1",
                ),
            ),
            "L2": PinInfo(
                name="SD0_D0",
                reg_addr=50335780,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "SDIO0_D_0",
                    "CAM_MCLK1",
                    "SPI0_SDI",
                    "XGPIOA_9",
                    "UART3_TX",
                    "PWM_13",
                    "WG0_D0",
                    "DBG_2",
                ),
            ),
            "K3": PinInfo(
                name="SD0_D1",
                reg_addr=50335784,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "SDIO0_D_1",
                    "IIC1_SDA",
                    "AUX0",
                    "XGPIOA_10",
                    "UART1_TX",
                    "PWM_12",
                    "WG0_D1",
                    "DBG_3",
                ),
            ),
            "M2": PinInfo(
                name="SD0_D2",
                reg_addr=50335788,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "SDIO0_D_2",
                    "IIC1_SCL",
                    "AUX1",
                    "XGPIOA_11",
                    "UART1_RX",
                    "PWM_11",
                    "WG1_D0",
                    "DBG_4",
                ),
            ),
            "M1": PinInfo(
                name="SD0_D3",
                reg_addr=50335792,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "SDIO0_D_3",
                    "CAM_MCLK0",
                    "SPI0_CS_X",
                    "XGPIOA_12",
                    "UART3_RX",
                    "PWM_10",
                    "WG1_D1",
                    "DBG_5",
                ),
            ),
            "K2": PinInfo(
                name="SD0_CD",
                reg_addr=50335796,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 3),
                funcs=("SDIO0_CD", "XGPIOA_13"),
            ),
            "N1": PinInfo(
                name="SD0_PWR_EN",
                reg_addr=50335800,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 3),
                funcs=("SDIO0_PWR_EN", "XGPIOA_14"),
            ),
            "N3": PinInfo(
                name="SPK_EN",
                reg_addr=50335804,
                bit_offset=0,
                bit_width=3,
                func_regs=(3,),
                funcs=("XGPIOA_15",),
            ),
            "M5": PinInfo(
                name="UART0_TX",
                reg_addr=50335808,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 7),
                funcs=(
                    "UART0_TX",
                    "CAM_MCLK1",
                    "PWM_4",
                    "XGPIOA_16",
                    "UART1_TX",
                    "AUX1",
                    "DBG_6",
                ),
            ),
            "M4": PinInfo(
                name="UART0_RX",
                reg_addr=50335812,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 7),
                funcs=(
                    "UART0_RX",
                    "CAM_MCLK0",
                    "PWM_5",
                    "XGPIOA_17",
                    "UART1_RX",
                    "AUX0",
                    "DBG_7",
                ),
            ),
            "P4": PinInfo(
                name="EMMC_RSTN",
                reg_addr=50335816,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 3, 4),
                funcs=("EMMC_RSTN", "XGPIOA_21", "AUX2"),
            ),
            "P3": PinInfo(
                name="EMMC_DAT2",
                reg_addr=50335820,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3),
                funcs=("EMMC_DAT_2", "SPINOR_HOLD_X", "SPINAND_HOLD", "XGPIOA_26"),
            ),
            "R4": PinInfo(
                name="EMMC_CLK",
                reg_addr=50335824,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3),
                funcs=("EMMC_CLK", "SPINOR_SCK", "SPINAND_CLK", "XGPIOA_22"),
            ),
            "P2": PinInfo(
                name="EMMC_DAT0",
                reg_addr=50335828,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3),
                funcs=("EMMC_DAT_0", "SPINOR_MOSI", "SPINAND_MOSI", "XGPIOA_25"),
            ),
            "P1": PinInfo(
                name="EMMC_DAT3",
                reg_addr=50335832,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3),
                funcs=("EMMC_DAT_3", "SPINOR_WP_X", "SPINAND_WP", "XGPIOA_27"),
            ),
            "R3": PinInfo(
                name="EMMC_CMD",
                reg_addr=50335836,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3),
                funcs=("EMMC_CMD", "SPINOR_MISO", "SPINAND_MISO", "XGPIOA_23"),
            ),
            "R2": PinInfo(
                name="EMMC_DAT1",
                reg_addr=50335840,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3),
                funcs=("EMMC_DAT_1", "SPINOR_CS_X", "SPINAND_CS", "XGPIOA_24"),
            ),
            "N6": PinInfo(
                name="JTAG_CPU_TMS",
                reg_addr=50335844,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "CV_2WTMS_CR_4WTMS",
                    "CAM_MCLK0",
                    "PWM_7",
                    "XGPIOA_19",
                    "UART1_RTS",
                    "AUX0",
                    "UART1_TX",
                    "VO_D_28",
                ),
            ),
            "N4": PinInfo(
                name="JTAG_CPU_TCK",
                reg_addr=50335848,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "CV_2WTCK_CR_4WTCK",
                    "CAM_MCLK1",
                    "PWM_6",
                    "XGPIOA_18",
                    "UART1_CTS",
                    "AUX1",
                    "UART1_RX",
                    "VO_D_29",
                ),
            ),
            "M6": PinInfo(
                name="JTAG_CPU_TRST",
                reg_addr=50335852,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 3, 6),
                funcs=("JTAG_CPU_TRST", "XGPIOA_20", "VO_D_30"),
            ),
            "R6": PinInfo(
                name="IIC0_SCL",
                reg_addr=50335856,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 5, 7),
                funcs=(
                    "CV_SCL0",
                    "UART1_TX",
                    "UART2_TX",
                    "XGPIOA_28",
                    "WG0_D0",
                    "DBG_10",
                ),
            ),
            "P6": PinInfo(
                name="IIC0_SDA",
                reg_addr=50335860,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 5, 6, 7),
                funcs=(
                    "CV_SDA0",
                    "UART1_RX",
                    "UART2_RX",
                    "XGPIOA_29",
                    "WG0_D1",
                    "WG1_D0",
                    "DBG_11",
                ),
            ),
            "P5": PinInfo(
                name="AUX0",
                reg_addr=50335864,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 3, 4, 5, 6, 7),
                funcs=("AUX0", "XGPIOA_30", "IIS1_MCLK", "VO_D_31", "WG1_D1", "DBG_12"),
            ),
            "P11": PinInfo(
                name="PWR_VBAT_DET",
                reg_addr=50335868,
                bit_offset=0,
                bit_width=3,
                func_regs=(0,),
                funcs=("PWR_VBAT_DET",),
            ),
            "R11": PinInfo(
                name="PWR_RSTN",
                reg_addr=50335872,
                bit_offset=0,
                bit_width=3,
                func_regs=(0,),
                funcs=("PWR_RSTN",),
            ),
            "P12": PinInfo(
                name="PWR_SEQ1",
                reg_addr=50335876,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 3),
                funcs=("PWR_SEQ1", "PWR_GPIO_3"),
            ),
            "R12": PinInfo(
                name="PWR_SEQ2",
                reg_addr=50335880,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 3),
                funcs=("PWR_SEQ2", "PWR_GPIO_4"),
            ),
            "P10": PinInfo(
                name="PWR_SEQ3",
                reg_addr=50335884,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 3),
                funcs=("PWR_SEQ3", "PWR_GPIO_5"),
            ),
            "N12": PinInfo(
                name="PWR_WAKEUP0",
                reg_addr=50335888,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "PWR_WAKEUP0",
                    "PWR_IR0",
                    "PWR_UART0_TX",
                    "PWR_GPIO_6",
                    "UART1_TX",
                    "IIC4_SCL",
                    "EPHY_LNK_LED",
                    "WG2_D0",
                ),
            ),
            "N11": PinInfo(
                name="PWR_WAKEUP1",
                reg_addr=50335892,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 3, 4, 5, 6, 7),
                funcs=(
                    "PWR_WAKEUP1",
                    "PWR_IR1",
                    "PWR_GPIO_7",
                    "UART1_TX",
                    "IIC4_SCL",
                    "EPHY_LNK_LED",
                    "WG0_D0",
                ),
            ),
            "P13": PinInfo(
                name="PWR_BUTTON1",
                reg_addr=50335896,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 3, 4, 5, 6, 7),
                funcs=(
                    "PWR_BUTTON1",
                    "PWR_GPIO_8",
                    "UART1_RX",
                    "IIC4_SDA",
                    "EPHY_SPD_LED",
                    "WG2_D1",
                ),
            ),
            "M11": PinInfo(
                name="PWR_ON",
                reg_addr=50335900,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 3, 4, 5, 6, 7),
                funcs=(
                    "PWR_ON",
                    "PWR_GPIO_9",
                    "UART1_RX",
                    "IIC4_SDA",
                    "EPHY_SPD_LED",
                    "WG0_D1",
                ),
            ),
            "R13": PinInfo(
                name="XTAL_XIN",
                reg_addr=50335904,
                bit_offset=0,
                bit_width=3,
                func_regs=(0,),
                funcs=("PWR_XTAL_CLKIN",),
            ),
            "M13": PinInfo(
                name="PWR_GPIO0",
                reg_addr=50335908,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 4),
                funcs=("PWR_GPIO_0", "UART2_TX", "PWR_UART0_RX", "PWM_8"),
            ),
            "N13": PinInfo(
                name="PWR_GPIO1",
                reg_addr=50335912,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 3, 4, 5, 6, 7),
                funcs=(
                    "PWR_GPIO_1",
                    "UART2_RX",
                    "EPHY_LNK_LED",
                    "PWM_9",
                    "PWR_IIC_SCL",
                    "IIC2_SCL",
                    "CV_4WTMS_CR_SDA0",
                ),
            ),
            "M12": PinInfo(
                name="PWR_GPIO2",
                reg_addr=50335916,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "PWR_GPIO_2",
                    "PWR_SECTICK",
                    "EPHY_SPD_LED",
                    "PWM_10",
                    "PWR_IIC_SDA",
                    "IIC2_SDA",
                    "CV_4WTCK_CR_2WTCK",
                ),
            ),
            "L14": PinInfo(
                name="CLK32K",
                reg_addr=50335920,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "CLK32K",
                    "AUX0",
                    "CV_4WTDI_CR_SCL0",
                    "PWR_GPIO_10",
                    "PWM_2",
                    "KEY_COL0",
                    "CAM_MCLK0",
                    "DBG_0",
                ),
            ),
            "M14": PinInfo(
                name="CLK25M",
                reg_addr=50335924,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "CLK25M",
                    "AUX1",
                    "CV_4WTDO_CR_2WTMS",
                    "PWR_GPIO_11",
                    "PWM_3",
                    "KEY_COL1",
                    "CAM_MCLK1",
                    "DBG_1",
                ),
            ),
            "J13": PinInfo(
                name="IIC2_SCL",
                reg_addr=50335928,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 3, 4, 7),
                funcs=("IIC2_SCL", "PWM_14", "PWR_GPIO_12", "UART2_RX", "KEY_COL2"),
            ),
            "J14": PinInfo(
                name="IIC2_SDA",
                reg_addr=50335932,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 3, 4, 5, 6, 7),
                funcs=(
                    "IIC2_SDA",
                    "PWM_15",
                    "PWR_GPIO_13",
                    "UART2_TX",
                    "IIS1_MCLK",
                    "IIS2_MCLK",
                    "KEY_COL3",
                ),
            ),
            "K15": PinInfo(
                name="UART2_TX",
                reg_addr=50335936,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "UART2_TX",
                    "PWM_11",
                    "PWR_UART1_TX",
                    "PWR_GPIO_14",
                    "KEY_ROW3",
                    "UART4_TX",
                    "IIS2_BCLK",
                    "WG2_D0",
                ),
            ),
            "L15": PinInfo(
                name="UART2_RTS",
                reg_addr=50335940,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 3, 4, 5, 6, 7),
                funcs=(
                    "UART2_RTS",
                    "PWM_8",
                    "PWR_GPIO_15",
                    "KEY_ROW0",
                    "UART4_RTS",
                    "IIS2_DO",
                    "WG1_D0",
                ),
            ),
            "K13": PinInfo(
                name="UART2_RX",
                reg_addr=50335944,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "UART2_RX",
                    "PWM_10",
                    "PWR_UART1_RX",
                    "PWR_GPIO_16",
                    "KEY_COL3",
                    "UART4_RX",
                    "IIS2_DI",
                    "WG2_D1",
                ),
            ),
            "K14": PinInfo(
                name="UART2_CTS",
                reg_addr=50335948,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 3, 4, 5, 6, 7),
                funcs=(
                    "UART2_CTS",
                    "PWM_9",
                    "PWR_GPIO_17",
                    "KEY_ROW1",
                    "UART4_CTS",
                    "IIS2_LRCK",
                    "WG1_D1",
                ),
            ),
            "G13": PinInfo(
                name="SD1_D3",
                reg_addr=50335952,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "PWR_SD1_D3_VO32",
                    "SPI2_CS_X",
                    "IIC1_SCL",
                    "PWR_GPIO_18",
                    "CAM_MCLK0",
                    "UART3_CTS",
                    "PWR_SPINOR1_CS_X",
                    "PWM_4",
                ),
            ),
            "F14": PinInfo(
                name="SD1_D2",
                reg_addr=50335956,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "PWR_SD1_D2_VO33",
                    "IIC1_SCL",
                    "UART2_TX",
                    "PWR_GPIO_19",
                    "CAM_MCLK0",
                    "UART3_TX",
                    "PWR_SPINOR1_HOLD_X",
                    "PWM_5",
                ),
            ),
            "H14": PinInfo(
                name="SD1_D1",
                reg_addr=50335960,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "PWR_SD1_D1_VO34",
                    "IIC1_SDA",
                    "UART2_RX",
                    "PWR_GPIO_20",
                    "CAM_MCLK1",
                    "UART3_RX",
                    "PWR_SPINOR1_WP_X",
                    "PWM_6",
                ),
            ),
            "H15": PinInfo(
                name="SD1_D0",
                reg_addr=50335964,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "PWR_SD1_D0_VO35",
                    "SPI2_SDI",
                    "IIC1_SDA",
                    "PWR_GPIO_21",
                    "CAM_MCLK1",
                    "UART3_RTS",
                    "PWR_SPINOR1_MISO",
                    "PWM_7",
                ),
            ),
            "G15": PinInfo(
                name="SD1_CMD",
                reg_addr=50335968,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "PWR_SD1_CMD_VO36",
                    "SPI2_SDO",
                    "IIC3_SCL",
                    "PWR_GPIO_22",
                    "CAM_VS0",
                    "EPHY_LNK_LED",
                    "PWR_SPINOR1_MOSI",
                    "PWM_8",
                ),
            ),
            "G14": PinInfo(
                name="SD1_CLK",
                reg_addr=50335972,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "PWR_SD1_CLK_VO37",
                    "SPI2_SCK",
                    "IIC3_SDA",
                    "PWR_GPIO_23",
                    "CAM_HS0",
                    "EPHY_SPD_LED",
                    "PWR_SPINOR1_SCK",
                    "PWM_9",
                ),
            ),
            "H12": PinInfo(
                name="RSTN",
                reg_addr=50335976,
                bit_offset=0,
                bit_width=3,
                func_regs=(0,),
                funcs=("RSTN",),
            ),
            "H13": PinInfo(
                name="PWM0_BUCK",
                reg_addr=50335980,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 3),
                funcs=("PWM_0", "XGPIOB_0"),
            ),
            "E15": PinInfo(
                name="ADC3",
                reg_addr=50335984,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "CAM_MCLK0",
                    "IIC4_SCL",
                    "XGPIOB_1",
                    "PWM_12",
                    "EPHY_LNK_LED",
                    "WG2_D0",
                    "UART3_TX",
                ),
            ),
            "E14": PinInfo(
                name="ADC2",
                reg_addr=50335988,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "CAM_MCLK1",
                    "IIC4_SDA",
                    "XGPIOB_2",
                    "PWM_13",
                    "EPHY_SPD_LED",
                    "WG2_D1",
                    "UART3_RX",
                ),
            ),
            "E13": PinInfo(
                name="ADC1",
                reg_addr=50335992,
                bit_offset=0,
                bit_width=3,
                func_regs=(3, 4),
                funcs=("XGPIOB_3", "KEY_COL2"),
            ),
            "B13": PinInfo(
                name="USB_ID",
                reg_addr=50335996,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 3),
                funcs=("USB_ID", "XGPIOB_4"),
            ),
            "C12": PinInfo(
                name="USB_VBUS_EN",
                reg_addr=50336000,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 3),
                funcs=("USB_VBUS_EN", "XGPIOB_5"),
            ),
            "PKG_TYPE0": PinInfo(
                name="PKG_TYPE0",
                reg_addr=50336004,
                bit_offset=0,
                bit_width=3,
                func_regs=(0,),
                funcs=("PKG_TYPE0",),
            ),
            "A13": PinInfo(
                name="USB_VBUS_DET",
                reg_addr=50336008,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 3, 4, 5),
                funcs=("USB_VBUS_DET", "XGPIOB_6", "CAM_MCLK0", "CAM_MCLK1"),
            ),
            "PKG_TYPE1": PinInfo(
                name="PKG_TYPE1",
                reg_addr=50336012,
                bit_offset=0,
                bit_width=3,
                func_regs=(0,),
                funcs=("PKG_TYPE1",),
            ),
            "PKG_TYPE2": PinInfo(
                name="PKG_TYPE2",
                reg_addr=50336016,
                bit_offset=0,
                bit_width=3,
                func_regs=(0,),
                funcs=("PKG_TYPE2",),
            ),
            "MUX_SPI1_MISO": PinInfo(
                name="MUX_SPI1_MISO",
                reg_addr=50336024,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "UART3_RTS",
                    "IIC1_SDA",
                    "XGPIOB_8",
                    "PWM_9",
                    "KEY_COL1",
                    "SPI1_SDI",
                    "DBG_14",
                ),
            ),
            "MUX_SPI1_MOSI": PinInfo(
                name="MUX_SPI1_MOSI",
                reg_addr=50336028,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "UART3_RX",
                    "IIC1_SCL",
                    "XGPIOB_7",
                    "PWM_8",
                    "KEY_COL0",
                    "SPI1_SDO",
                    "DBG_13",
                ),
            ),
            "MUX_SPI1_CS": PinInfo(
                name="MUX_SPI1_CS",
                reg_addr=50336032,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "UART3_CTS",
                    "CAM_MCLK0",
                    "XGPIOB_10",
                    "PWM_11",
                    "KEY_ROW3",
                    "SPI1_CS_X",
                    "DBG_16",
                ),
            ),
            "MUX_SPI1_SCK": PinInfo(
                name="MUX_SPI1_SCK",
                reg_addr=50336036,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "UART3_TX",
                    "CAM_MCLK1",
                    "XGPIOB_9",
                    "PWM_10",
                    "KEY_ROW2",
                    "SPI1_SCK",
                    "DBG_15",
                ),
            ),
            "D15": PinInfo(
                name="PAD_ETH_TXP___EPHY_RXN",
                reg_addr=50336040,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "UART3_RX",
                    "IIC1_SCL",
                    "XGPIOB_25",
                    "PWM_13",
                    "CAM_MCLK0",
                    "SPI1_SDO",
                    "IIS2_LRCK",
                ),
            ),
            "D14": PinInfo(
                name="PAD_ETH_TXM___EPHY_RXP",
                reg_addr=50336044,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "UART3_RTS",
                    "IIC1_SDA",
                    "XGPIOB_24",
                    "PWM_12",
                    "CAM_MCLK1",
                    "SPI1_SDI",
                    "IIS2_BCLK",
                ),
            ),
            "C14": PinInfo(
                name="PAD_ETH_RXP___EPHY_TXN",
                reg_addr=50336048,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "UART3_TX",
                    "CAM_MCLK1",
                    "XGPIOB_27",
                    "PWM_15",
                    "CAM_HS0",
                    "SPI1_SCK",
                    "IIS2_DO",
                ),
            ),
            "B15": PinInfo(
                name="PAD_ETH_RXM___EPHY_TXP",
                reg_addr=50336052,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "UART3_CTS",
                    "CAM_MCLK0",
                    "XGPIOB_26",
                    "PWM_14",
                    "CAM_VS0",
                    "SPI1_CS_X",
                    "IIS2_DI",
                ),
            ),
            "A12": PinInfo(
                name="VIVO_D10",
                reg_addr=50336056,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "PWM_1",
                    "VI1_D_10",
                    "VO_D_23",
                    "XGPIOB_11",
                    "RMII0_IRQ",
                    "CAM_MCLK0",
                    "IIC1_SDA",
                    "UART2_TX",
                ),
            ),
            "B12": PinInfo(
                name="VIVO_D9",
                reg_addr=50336060,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 5, 6, 7),
                funcs=(
                    "PWM_2",
                    "VI1_D_9",
                    "VO_D_22",
                    "XGPIOB_12",
                    "CAM_MCLK1",
                    "IIC1_SCL",
                    "UART2_RX",
                ),
            ),
            "C11": PinInfo(
                name="VIVO_D8",
                reg_addr=50336064,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "PWM_3",
                    "VI1_D_8",
                    "VO_D_21",
                    "XGPIOB_13",
                    "RMII0_MDIO",
                    "SPI3_SDO",
                    "IIC2_SCL",
                    "CAM_VS0",
                ),
            ),
            "B11": PinInfo(
                name="VIVO_D7",
                reg_addr=50336068,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "VI2_D_7",
                    "VI1_D_7",
                    "VO_D_20",
                    "XGPIOB_14",
                    "RMII0_RXD1",
                    "SPI3_SDI",
                    "IIC2_SDA",
                    "CAM_HS0",
                ),
            ),
            "C10": PinInfo(
                name="VIVO_D6",
                reg_addr=50336072,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "VI2_D_6",
                    "VI1_D_6",
                    "VO_D_19",
                    "XGPIOB_15",
                    "RMII0_REFCLKI",
                    "SPI3_SCK",
                    "UART2_TX",
                    "CAM_VS0",
                ),
            ),
            "B10": PinInfo(
                name="VIVO_D5",
                reg_addr=50336076,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "VI2_D_5",
                    "VI1_D_5",
                    "VO_D_18",
                    "XGPIOB_16",
                    "RMII0_RXD0",
                    "SPI3_CS_X",
                    "UART2_RX",
                    "CAM_HS0",
                ),
            ),
            "D10": PinInfo(
                name="VIVO_D4",
                reg_addr=50336080,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "VI2_D_4",
                    "VI1_D_4",
                    "VO_D_17",
                    "XGPIOB_17",
                    "RMII0_MDC",
                    "IIC1_SDA",
                    "UART2_CTS",
                    "CAM_VS0",
                ),
            ),
            "A10": PinInfo(
                name="VIVO_D3",
                reg_addr=50336084,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "VI2_D_3",
                    "VI1_D_3",
                    "VO_D_16",
                    "XGPIOB_18",
                    "RMII0_TXD0",
                    "IIC1_SCL",
                    "UART2_RTS",
                    "CAM_HS0",
                ),
            ),
            "A9": PinInfo(
                name="VIVO_D2",
                reg_addr=50336088,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "VI2_D_2",
                    "VI1_D_2",
                    "VO_D_15",
                    "XGPIOB_19",
                    "RMII0_TXD1",
                    "CAM_MCLK1",
                    "PWM_2",
                    "UART2_TX",
                ),
            ),
            "B9": PinInfo(
                name="VIVO_D1",
                reg_addr=50336092,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "VI2_D_1",
                    "VI1_D_1",
                    "VO_D_14",
                    "XGPIOB_20",
                    "RMII0_RXDV",
                    "IIC3_SDA",
                    "PWM_3",
                    "IIC4_SCL",
                ),
            ),
            "E10": PinInfo(
                name="VIVO_D0",
                reg_addr=50336096,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "VI2_D_0",
                    "VI1_D_0",
                    "VO_D_13",
                    "XGPIOB_21",
                    "RMII0_TXCLK",
                    "IIC3_SCL",
                    "WG1_D0",
                    "IIC4_SDA",
                ),
            ),
            "C9": PinInfo(
                name="VIVO_CLK",
                reg_addr=50336100,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "VI2_CLK",
                    "VI1_CLK",
                    "VO_CLK1",
                    "XGPIOB_22",
                    "RMII0_TXEN",
                    "CAM_MCLK0",
                    "WG1_D1",
                    "UART2_RX",
                ),
            ),
            "B8": PinInfo(
                name="PAD_MIPIRX5N",
                reg_addr=50336104,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 5, 6, 7),
                funcs=(
                    "VI1_D_11",
                    "VO_D_12",
                    "XGPIOC_0",
                    "CAM_MCLK0",
                    "WG0_D0",
                    "DBG_0",
                ),
            ),
            "C8": PinInfo(
                name="PAD_MIPIRX5P",
                reg_addr=50336108,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "VI1_D_12",
                    "VO_D_11",
                    "XGPIOC_1",
                    "IIS1_MCLK",
                    "CAM_MCLK1",
                    "WG0_D1",
                    "DBG_1",
                ),
            ),
            "B7": PinInfo(
                name="PAD_MIPIRX4N",
                reg_addr=50336112,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "CV_4WTDI_CR_SCL0",
                    "VI0_CLK",
                    "VI1_D_13",
                    "XGPIOC_2",
                    "IIC1_SDA",
                    "CAM_MCLK0",
                    "KEY_ROW0",
                    "MUX_SPI1_SCK",
                ),
            ),
            "A7": PinInfo(
                name="PAD_MIPIRX4P",
                reg_addr=50336116,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "CV_4WTMS_CR_SDA0",
                    "VI0_D_0",
                    "VI1_D_14",
                    "XGPIOC_3",
                    "IIC1_SCL",
                    "CAM_MCLK1",
                    "KEY_ROW1",
                    "MUX_SPI1_CS",
                ),
            ),
            "C7": PinInfo(
                name="PAD_MIPIRX3N",
                reg_addr=50336120,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 7),
                funcs=(
                    "CV_4WTDO_CR_2WTMS",
                    "VI0_D_1",
                    "VI1_D_15",
                    "XGPIOC_4",
                    "CAM_MCLK0",
                    "MUX_SPI1_MISO",
                ),
            ),
            "A6": PinInfo(
                name="PAD_MIPIRX3P",
                reg_addr=50336124,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 7),
                funcs=(
                    "CV_4WTCK_CR_2WTCK",
                    "VI0_D_2",
                    "VI1_D_16",
                    "XGPIOC_5",
                    "MUX_SPI1_MOSI",
                ),
            ),
            "B6": PinInfo(
                name="PAD_MIPIRX2N",
                reg_addr=50336128,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 5, 7),
                funcs=(
                    "VI0_D_3",
                    "VO_D_10",
                    "XGPIOC_6",
                    "VI1_D_17",
                    "IIC4_SCL",
                    "DBG_6",
                ),
            ),
            "C6": PinInfo(
                name="PAD_MIPIRX2P",
                reg_addr=50336132,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 5, 7),
                funcs=(
                    "VI0_D_4",
                    "VO_D_9",
                    "XGPIOC_7",
                    "VI1_D_18",
                    "IIC4_SDA",
                    "DBG_7",
                ),
            ),
            "B5": PinInfo(
                name="PAD_MIPIRX1N",
                reg_addr=50336136,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 6, 7),
                funcs=("VI0_D_5", "VO_D_8", "XGPIOC_8", "KEY_ROW3", "DBG_8"),
            ),
            "C5": PinInfo(
                name="PAD_MIPIRX1P",
                reg_addr=50336140,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 6, 7),
                funcs=(
                    "VI0_D_6",
                    "VO_D_7",
                    "XGPIOC_9",
                    "IIC1_SDA",
                    "KEY_ROW2",
                    "DBG_9",
                ),
            ),
            "A4": PinInfo(
                name="PAD_MIPIRX0N",
                reg_addr=50336144,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 5, 7),
                funcs=(
                    "VI0_D_7",
                    "VO_D_6",
                    "XGPIOC_10",
                    "IIC1_SCL",
                    "CAM_MCLK1",
                    "DBG_10",
                ),
            ),
            "B4": PinInfo(
                name="PAD_MIPIRX0P",
                reg_addr=50336148,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 7),
                funcs=("VI0_D_8", "VO_D_5", "XGPIOC_11", "CAM_MCLK0", "DBG_11"),
            ),
            "A2": PinInfo(
                name="PAD_MIPI_TXM4",
                reg_addr=50336152,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "VI0_D_15",
                    "SD1_CLK",
                    "VO_D_24",
                    "XGPIOC_18",
                    "CAM_MCLK1",
                    "PWM_12",
                    "IIC1_SDA",
                    "DBG_18",
                ),
            ),
            "B3": PinInfo(
                name="PAD_MIPI_TXP4",
                reg_addr=50336156,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "VI0_D_16",
                    "SD1_CMD",
                    "VO_D_25",
                    "XGPIOC_19",
                    "CAM_MCLK0",
                    "PWM_13",
                    "IIC1_SCL",
                    "DBG_19",
                ),
            ),
            "B2": PinInfo(
                name="PAD_MIPI_TXM3",
                reg_addr=50336160,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "VI0_D_17",
                    "SD1_D0",
                    "VO_D_26",
                    "XGPIOC_20",
                    "IIC2_SDA",
                    "PWM_14",
                    "IIC1_SDA",
                    "CAM_VS0",
                ),
            ),
            "B1": PinInfo(
                name="PAD_MIPI_TXP3",
                reg_addr=50336164,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "VI0_D_18",
                    "SD1_D1",
                    "VO_D_27",
                    "XGPIOC_21",
                    "IIC2_SCL",
                    "PWM_15",
                    "IIC1_SCL",
                    "CAM_HS0",
                ),
            ),
            "C2": PinInfo(
                name="PAD_MIPI_TXM2",
                reg_addr=50336168,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "CV_4WTMS_CR_SDA0",
                    "VI0_D_13",
                    "VO_D_0",
                    "XGPIOC_16",
                    "IIC1_SDA",
                    "PWM_8",
                    "SPI0_SCK",
                    "SD1_D2",
                ),
            ),
            "C1": PinInfo(
                name="PAD_MIPI_TXP2",
                reg_addr=50336172,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "CV_4WTDI_CR_SCL0",
                    "VI0_D_14",
                    "VO_CLK0",
                    "XGPIOC_17",
                    "IIC1_SCL",
                    "PWM_9",
                    "SPI0_CS_X",
                    "SD1_D3",
                ),
            ),
            "D2": PinInfo(
                name="PAD_MIPI_TXM1",
                reg_addr=50336176,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "CV_4WTDO_CR_2WTMS",
                    "VI0_D_11",
                    "VO_D_2",
                    "XGPIOC_14",
                    "IIC2_SDA",
                    "PWM_10",
                    "SPI0_SDO",
                    "DBG_14",
                ),
            ),
            "D1": PinInfo(
                name="PAD_MIPI_TXP1",
                reg_addr=50336180,
                bit_offset=0,
                bit_width=3,
                func_regs=(0, 1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "CV_4WTCK_CR_2WTCK",
                    "VI0_D_12",
                    "VO_D_1",
                    "XGPIOC_15",
                    "IIC2_SCL",
                    "PWM_11",
                    "SPI0_SDI",
                    "DBG_15",
                ),
            ),
            "E2": PinInfo(
                name="PAD_MIPI_TXM0",
                reg_addr=50336184,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "VI0_D_9",
                    "VO_D_4",
                    "XGPIOC_12",
                    "CAM_MCLK1",
                    "PWM_14",
                    "CAM_VS0",
                    "DBG_12",
                ),
            ),
            "E1": PinInfo(
                name="PAD_MIPI_TXP0",
                reg_addr=50336188,
                bit_offset=0,
                bit_width=3,
                func_regs=(1, 2, 3, 4, 5, 6, 7),
                funcs=(
                    "VI0_D_10",
                    "VO_D_3",
                    "XGPIOC_13",
                    "CAM_MCLK0",
                    "PWM_15",
                    "CAM_HS0",
                    "DBG_13",
                ),
            ),
            "H1": PinInfo(
                name="PAD_AUD_AINL_MIC",
                reg_addr=50336192,
                bit_offset=0,
                bit_width=3,
                func_regs=(3, 4, 5),
                funcs=("XGPIOC_23", "IIS1_BCLK", "IIS2_BCLK"),
            ),
            "J1": PinInfo(
                name="PAD_AUD_AINR_MIC",
                reg_addr=50336196,
                bit_offset=0,
                bit_width=3,
                func_regs=(3, 4, 5, 6),
                funcs=("XGPIOC_22", "IIS1_DO", "IIS2_DI", "IIS1_DI"),
            ),
            "F2": PinInfo(
                name="PAD_AUD_AOUTL",
                reg_addr=50336200,
                bit_offset=0,
                bit_width=3,
                func_regs=(3, 4, 5),
                funcs=("XGPIOC_25", "IIS1_LRCK", "IIS2_LRCK"),
            ),
            "G2": PinInfo(
                name="PAD_AUD_AOUTR",
                reg_addr=50336204,
                bit_offset=0,
                bit_width=3,
                func_regs=(3, 4, 5, 6),
                funcs=("XGPIOC_24", "IIS1_DI", "IIS2_DO", "IIS1_DO"),
            ),
            "C15": PinInfo(
                name="GPIO_RTX___EPHY_RTX",
                reg_addr=50336208,
                bit_offset=0,
                bit_width=3,
                func_regs=(3, 4, 5),
                funcs=("XGPIOB_23", "PWM_1", "CAM_MCLK0"),
            ),
            "R10": PinInfo(
                name="GPIO_ZQ___PAD_ZQ",
                reg_addr=50336212,
                bit_offset=0,
                bit_width=3,
                func_regs=(3, 4),
                funcs=("PWR_GPIO_24", "PWM_2"),
            ),
        },
        adc={
            "ADCBTN": ADCInfo(
                pin="E15",
                pin_func="XGPIOB_1",
                sysfs="/sys/bus/iio/devices/iio:device0/in_voltage3_raw",
                resolution=12,
                vref=1.5,
                init_cmd="test -e /sys/bus/iio/devices/iio:device0 || { insmod /system/ko/industrialio.ko; insmod /system/ko/cv184x_saradc.ko; }",
            ),
        },
        softkey={
            "A": SoftKeyInfo(
                gpio=None,
                adc="ADCBTN",
                raw_values=(1912, 3076),
                raw_tolerance=100,
            ),
            "B": SoftKeyInfo(
                gpio=None,
                adc="ADCBTN",
                raw_values=(2486, 3076),
                raw_tolerance=100,
            ),
        },
        gpio={
            "LED": GPIOInfo(
                pin="P3",
                pin_func="XGPIOA_26",
                chip=0,  # /dev/gpiochip0
                num=26,
            ),
            # "GPIOBTNBOOT": GPIOInfo(
            #     pin="J14",
            #     pin_func="PWR_GPIO_13",
            #     chip=?,  # /dev/gpiochip?
            #     num=?,
            # ),
        },
        i2c={
            "I2C0": I2CInfo(
                dev="/dev/i2c-2",
                scl="B1",
                sda="B2",
                scl_func="IIC2_SCL",
                sda_func="IIC2_SDA",
            ),
            "I2C1": I2CInfo(
                dev="/dev/i2c-1",  # not yet enabled in dts
                scl="A10",
                sda="D10",
                scl_func="IIC1_SCL",
                sda_func="IIC1_SDA",
            ),
            "I2C2": I2CInfo(
                dev="/dev/i2c-4",
                scl="B9",
                sda="E10",
                scl_func="IIC4_SCL",
                sda_func="IIC4_SDA",
            ),
        },
        # for pwm please check
        # https://doc.sophgo.com/cvitek-develop-docs/master/docs_latest_release/CV184x/zh/01.software/BSP/Peripheral_Driver/build/html/10_PWM_Operation_Guide.html
        # https://developer.sophgo.com/thread/813.html
        # for appropriate configurations
        spi={
            "SPI0": SPIInfo(
                dev="/dev/spidev3.0",
                sclk="C10",
                mosi="C11",
                miso="B11",
                cs=None,
                sclk_func="SPI3_SCK",
                mosi_func="SPI3_SDO",
                miso_func="SPI3_SDI",
                cs_func=None,
            ),
            "SPI0.0": SPIInfo(
                dev="/dev/spidev3.0",
                sclk="C10",
                mosi="C11",
                miso="B11",
                cs="B10",
                sclk_func="SPI3_SCK",
                mosi_func="SPI3_SDO",
                miso_func="SPI3_SDI",
                cs_func="SPI3_CS_X",
            ),
        },
        uart={
            "UART1": UARTInfo(
                dev="/dev/ttyS0",
                tx="M5",
                rx="M4",
                tx_func="UART0_TX",
                rx_func="UART0_RX",
            ),
            "UART2": UARTInfo(
                dev="/dev/ttyS2",  # not yet enabled in dts
                tx="A12",
                rx="B12",
                tx_func="UART2_TX",
                rx_func="UART2_RX",
            ),
        },
        wdt=WDTInfo(
            init_cmd="test -e /dev/watchdog || insmod /system/ko/cv184x_wdt.ko",
        ),
    ),
)
