# ruff: noqa: E402
"""AXP2101 power management unit driver."""

from dara.device.pmu import PMU, PMUError, PMUPowerChannel, pmu_drivers
from dara.peripheral.i2c import I2C

class AXP2101Error(PMUError):
    """Raised when an AXP2101 operation cannot be completed."""
    ...


@pmu_drivers.register("axp2101")
class AXP2101(PMU):
    """An AXP2101 power management unit connected over I2C."""
    _STATUS1 = ...
    _STATUS2 = ...
    _VERSION = ...
    _COMMON_CONFIG = ...
    _CHARGE_GAUGE_WATCHDOG = ...
    _BATTERY_VOLTAGE_HIGH = ...
    _BATTERY_VOLTAGE_LOW = ...
    _DCDC_CONTROL = ...
    _LDO_CONTROL0 = ...
    _LDO_CONTROL1 = ...
    _BATTERY_PERCENT = ...
    _DEVICE_IDS = ...
    _POWER_BITS = ...
    def __init__(self, i2c: I2C, addr: int = ..., *, auto_open: bool = ...) -> None:
        """Create an AXP2101 on a caller-owned bus and optionally verify it."""
        ...

    def open(self) -> None:
        """Verify the AXP2101 chip identifier on its open I2C bus."""
        ...

    def close(self) -> None:
        """Deactivate the PMU without changing outputs or closing its bus."""
        ...

    def __enter__(self) -> AXP2101:
        """Open the PMU if needed and return it for a ``with`` statement."""
        ...

    def __exit__(self, *args: object) -> None:
        """Close the PMU when leaving a ``with`` statement."""
        ...

    @property
    def is_opened(self) -> bool:
        """Return whether the PMU is active on an open I2C bus."""
        ...

    def battery_voltage(self) -> int:
        """Return the battery voltage in millivolts."""
        ...

    def battery_percent(self) -> int:
        """Return battery percentage, or ``-1`` when no battery is connected."""
        ...

    def is_charging(self) -> bool:
        """Return whether the battery charging-status bit is set."""
        ...

    def set_power(self, channel: PMUPowerChannel, enable: bool) -> None:
        """Enable or disable one supported AXP2101 power channel."""
        ...

    def poweroff(self) -> None:
        """Synchronize filesystems and assert the software-poweroff bit."""
        ...

    def reboot(self) -> None:
        """Report that the AXP2101 has no hardware reboot operation."""
        ...
    @property
    def _bus(self) -> I2C: ...
    def _read(self, register: int) -> int: ...
    def _write(self, register: int, value: int) -> None: ...
