# ruff: noqa: E402
"""DIR + PWM motor control selected by board motor number."""

class MotorError(OSError): ...

class Motor:
    number: int
    def __init__(self, number: int, *, forward_high: bool = ..., auto_open: bool = ...) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Motor: ...
    def __exit__(self, *args: object) -> None: ...
    @property
    def is_opened(self) -> bool: ...
    def stop(self) -> None: ...
    def forward(self, speed: float = ...) -> None: ...
    def backward(self, speed: float = ...) -> None: ...
    def set_speed(self, speed: float) -> None: ...

class Wheel:
    def __init__(self, *, left_forward_high: bool = ..., right_forward_high: bool = ..., auto_open: bool = ...) -> None: ...
    @property
    def left(self) -> Motor: ...
    @property
    def right(self) -> Motor: ...
    @property
    def is_opened(self) -> bool: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Wheel: ...
    def __exit__(self, *args: object) -> None: ...
    def set_speed(self, left: float, right: float) -> None: ...
    def forward(self, speed: float = ...) -> None: ...
    def backward(self, speed: float = ...) -> None: ...
    def turn_left(self, speed: float = ...) -> None: ...
    def turn_right(self, speed: float = ...) -> None: ...
    def stop(self) -> None: ...

DCMotor = Motor
DCMotorError = MotorError
