# ruff: noqa: E402
"""DHT11 and DHT22 temperature and humidity sensor driver."""

from enum import Enum
from dara.peripheral.gpio import GPIOEdge, PollEvent
from dara.device.hs import HS, HSData, HSError, hs_drivers
from dara.device.ts import TS, TSData, TSError, ts_drivers

class DHTType(str, Enum):
    """DHT sensor models supported by the driver."""
    DHT11 = ...
    DHT22 = ...


class DHTError(TSError, HSError):
    """Raised when a DHT sensor operation cannot be completed."""
    ...


class DHTData(HSData, TSData):
    """Temperature and relative humidity from one DHT sample."""
    def __init__(self, temperature: float, humidity: float) -> None:
        """Initialize a DHT sample."""
        ...



@ts_drivers.register("dht")
@hs_drivers.register("dht")
class DHT(TS, HS):
    """A DHT11 or DHT22 sensor connected to a GPIO line."""
    _EDGE_TIMEOUT = ...
    _STABILIZE_DELAY = ...
    _START_LOW_DELAY = ...
    _MIN_READ_INTERVAL = ...
    def __init__(self, gpio: int | str, dht_type: DHTType = ..., *, temperature_offset: float = ..., humidity_offset: float = ..., pulse_threshold_us: float = ..., auto_open: bool = ...) -> None:
        """Create a DHT sensor on a GPIO identifier and optionally activate it."""
        ...

    def open(self) -> None:
        """Open the GPIO and activate the sensor."""
        ...

    def close(self) -> None:
        """Deactivate the sensor and close its GPIO."""
        ...

    def __enter__(self) -> DHT:
        """Open the sensor if needed and return it for a ``with`` statement."""
        ...

    def __exit__(self, *args: object) -> None:
        """Close the sensor when leaving a ``with`` statement."""
        ...

    @property
    def is_opened(self) -> bool:
        """Return whether the sensor and its GPIO are open."""
        ...

    def read_temperature(self) -> float:
        """Return the temperature in degrees Celsius."""
        ...

    def read_humidity(self) -> float:
        """Return the relative humidity as a percentage."""
        ...

    def read_all(self) -> DHTData:
        """Return temperature and relative humidity from one sample."""
        ...
    def _read_sample(self) -> DHTData: ...
    def _read_physical_sample(self) -> DHTData: ...
    def _receive_high_pulses(self) -> list[int]: ...
    def _next_edge(self) -> PollEvent: ...
    def _expect_edge(self, edge: GPIOEdge) -> PollEvent: ...
    def _decode_pulses(self, durations: list[int]) -> bytes: ...
    def _decode_payload(self, payload: bytes) -> DHTData: ...
