# ruff: noqa: E402
"""Shared inertial measurement unit types and behavior."""

from abc import ABC, abstractmethod
from enum import Enum, IntEnum

class IMUMode(str, Enum):
    """Sensor outputs enabled during sampling."""
    ACC_ONLY = ...
    GYRO_ONLY = ...
    DUAL = ...


class IMUAccScale(IntEnum):
    """Accelerometer full-scale ranges."""
    ACC_SCALE_2G = ...
    ACC_SCALE_4G = ...
    ACC_SCALE_8G = ...
    ACC_SCALE_16G = ...


class IMUAccOdr(Enum):
    """Accelerometer output data rates."""
    ACC_ODR_8000 = ...
    ACC_ODR_4000 = ...
    ACC_ODR_2000 = ...
    ACC_ODR_1000 = ...
    ACC_ODR_833 = ...
    ACC_ODR_500 = ...
    ACC_ODR_416 = ...
    ACC_ODR_250 = ...
    ACC_ODR_208 = ...
    ACC_ODR_128 = ...
    ACC_ODR_125 = ...
    ACC_ODR_104 = ...
    ACC_ODR_62_5 = ...
    ACC_ODR_52 = ...
    ACC_ODR_31_25 = ...
    ACC_ODR_26 = ...
    ACC_ODR_21 = ...
    ACC_ODR_12_5 = ...
    ACC_ODR_11 = ...
    ACC_ODR_3 = ...


class IMUGyroScale(IntEnum):
    """Gyroscope full-scale ranges."""
    GYRO_SCALE_16DPS = ...
    GYRO_SCALE_32DPS = ...
    GYRO_SCALE_64DPS = ...
    GYRO_SCALE_125DPS = ...
    GYRO_SCALE_128DPS = ...
    GYRO_SCALE_250DPS = ...
    GYRO_SCALE_256DPS = ...
    GYRO_SCALE_500DPS = ...
    GYRO_SCALE_512DPS = ...
    GYRO_SCALE_1000DPS = ...
    GYRO_SCALE_1024DPS = ...
    GYRO_SCALE_2000DPS = ...
    GYRO_SCALE_2048DPS = ...


class IMUGyroOdr(Enum):
    """Gyroscope output data rates."""
    GYRO_ODR_8000 = ...
    GYRO_ODR_4000 = ...
    GYRO_ODR_2000 = ...
    GYRO_ODR_1000 = ...
    GYRO_ODR_833 = ...
    GYRO_ODR_500 = ...
    GYRO_ODR_416 = ...
    GYRO_ODR_250 = ...
    GYRO_ODR_125 = ...
    GYRO_ODR_208 = ...
    GYRO_ODR_104 = ...
    GYRO_ODR_62_5 = ...
    GYRO_ODR_52 = ...
    GYRO_ODR_26 = ...
    GYRO_ODR_31_25 = ...
    GYRO_ODR_12_5 = ...


class IMUError(OSError):
    """Raised when an IMU operation cannot be completed."""
    ...


class IMUGyroCalibration:
    """Gyroscope zero-rate bias in degrees per second."""
    x: float
    """X-axis bias."""
    y: float
    """Y-axis bias."""
    z: float
    """Z-axis bias."""
    def __init__(self, x: float, y: float, z: float) -> None:
        """Initialize gyroscope bias values for all three axes."""
        ...



class IMUData:
    """Accelerometer and gyroscope data from an IMU capability read."""
    acc: tuple[float, float, float]
    """Acceleration along each axis, or zeros when unavailable."""
    gyro: tuple[float, float, float]
    """Angular velocity along each axis, or zeros when unavailable."""
    def __init__(self, acc: tuple[float, float, float], gyro: tuple[float, float, float]) -> None:
        """Initialize accelerometer and gyroscope samples."""
        ...



_CALIBRATION_PATH = ...
class IMU(ABC):
    """Abstract inertial measurement unit with shared gyro calibration support."""
    mode: IMUMode
    """Sensor outputs enabled during sampling."""
    calib_gyro_data: IMUGyroCalibration
    def __init__(self) -> None:
        """Initialize shared inertial measurement unit state."""
        ...

    @abstractmethod
    def open(self) -> None:
        """Open the device and initialize its sensor."""
        ...

    @abstractmethod
    def close(self) -> None:
        """Deactivate the device without closing its peripheral bus."""
        ...

    def __enter__(self) -> IMU:
        """Open the device if needed and return it for a ``with`` statement."""
        ...

    def __exit__(self, *args: object) -> None:
        """Close the device when leaving a ``with`` statement."""
        ...

    @property
    @abstractmethod
    def is_opened(self) -> bool:
        """Return whether the device is open."""
        ...

    @abstractmethod
    def read_imu(self, calib_gyro: bool = ..., radian: bool = ...) -> IMUData:
        """Return acceleration and optional calibrated or converted gyro data."""
        ...

    def _calibrate_gyro(self, gyro: tuple[float, float, float], calib_gyro: bool = ..., radian: bool = ...) -> tuple[float, float, float]: ...

    def calib_gyro(self, time_ms: int, interval_ms: int = ..., save_id: str = ...) -> IMUGyroCalibration:
        """Calculate gyro bias, optionally save it, and make it active."""
        ...

    def calib_gyro_exists(self, save_id: str = ...) -> bool:
        """Return whether a valid named gyro calibration is saved."""
        ...

    def load_calib_gyro(self, save_id: str = ...) -> IMUGyroCalibration:
        """Load and activate a named gyro calibration, or zero bias if absent."""
        ...

    def save_calib_gyro(self, calibration: IMUGyroCalibration, save_id: str = ...) -> None:
        """Save a gyro calibration under ``save_id`` and preserve other profiles."""
        ...
    @staticmethod
    def _validate_save_id(save_id: str) -> None: ...
    @staticmethod
    def _load_profiles() -> dict[str, object]: ...
    @staticmethod
    def _profile_calibration(profiles: dict[str, object], save_id: str) -> IMUGyroCalibration | None: ...



imu_drivers = ...
