# ruff: noqa: E402
"""LTR390 ambient-light and ultraviolet sensor driver."""

from enum import Enum, IntEnum
from dara.device.ls import LS, LSData, LSError, ls_drivers
from dara.peripheral.i2c import I2C

class LTR390Error(LSError):
    """Raised when an LTR390 sensor operation cannot be completed."""
    ...


class LTR390Mode(str, Enum):
    """Measurement channel selected by the sensor."""
    AMBIENT_LIGHT = ...
    ULTRAVIOLET = ...


class LTR390Gain(IntEnum):
    """Sensor gain multiplier."""
    GAIN_1X = ...
    GAIN_3X = ...
    GAIN_6X = ...
    GAIN_9X = ...
    GAIN_18X = ...


class LTR390Resolution(IntEnum):
    """Measurement resolution in bits."""
    RESOLUTION_20BIT = ...
    RESOLUTION_19BIT = ...
    RESOLUTION_18BIT = ...
    RESOLUTION_17BIT = ...
    RESOLUTION_16BIT = ...
    RESOLUTION_13BIT = ...


class LTR390Data(LSData):
    """LTR390 brightness in lux for ALS mode or UV Index for UVS mode."""
    brightness: float
    """Brightness in lux for ambient-light mode or UV Index for UV mode."""
    ...


@ls_drivers.register("ltr390")
class LTR390(LS):
    """An LTR390 ambient-light and ultraviolet sensor connected over I2C."""
    _MAIN_CTRL = ...
    _MEAS_RATE = ...
    _GAIN = ...
    _PART_ID = ...
    _MAIN_STATUS = ...
    _ALS_DATA = ...
    _UVS_DATA = ...
    _INT_CFG = ...
    _INT_PERSISTENCE = ...
    _THRESHOLD_UPPER = ...
    _THRESHOLD_LOWER = ...
    _GAIN_VALUES = ...
    _RESOLUTION_VALUES = ...
    _INTEGRATION_TIMES_MS = ...
    def __init__(self, i2c: I2C, addr: int = ..., mode: LTR390Mode = ..., gain: LTR390Gain = ..., resolution: LTR390Resolution = ..., threshold: tuple[int, int] | None = ..., *, window_factor: float = ..., auto_open: bool = ...) -> None:
        """Create an LTR390, with ``window_factor`` correcting optical loss."""
        ...

    def open(self) -> None:
        """Verify, reset, and enable the sensor on its open I2C bus."""
        ...

    def close(self) -> None:
        """Disable the sensor without closing its caller-owned I2C bus."""
        ...

    def __enter__(self) -> LTR390:
        """Open the sensor if needed and return it for a ``with`` statement."""
        ...

    def __exit__(self, *args: object) -> None:
        """Close the sensor when leaving a ``with`` statement."""
        ...

    @property
    def is_opened(self) -> bool:
        """Return whether the sensor is active on an open I2C bus."""
        ...

    def reset(self, mode: LTR390Mode | None = ..., gain: LTR390Gain | None = ..., resolution: LTR390Resolution | None = ..., threshold: tuple[int, int] | None = ...) -> None:
        """Update non-``None`` settings and reinitialize an open sensor."""
        ...

    def configure_interrupt(self, enabled: bool, source: LTR390Mode, persistence: int = ...) -> None:
        """Configure threshold interrupt enable, source, and persistence."""
        ...

    def is_data_ready(self) -> bool:
        """Return whether a new sample is available."""
        ...

    def read_brightness(self) -> float:
        """Return illuminance in lux or, in ultraviolet mode, UV Index."""
        ...

    def read_raw(self) -> int:
        """Return the unitless raw count from the active measurement mode."""
        ...

    def read_all(self) -> LTR390Data:
        """Return brightness in lux or, in ultraviolet mode, UV Index."""
        ...
    def _soft_reset(self) -> None: ...
    def _apply_configuration(self) -> None: ...
    def _set_enabled(self, enabled: bool) -> None: ...
    def _is_enabled(self) -> bool: ...
    @property
    def _bus(self) -> I2C: ...
    def _read(self, register: int) -> int: ...
    def _write(self, register: int, value: int) -> None: ...
    def _update(self, register: int, mask: int, value: int) -> None: ...
    def _read_data(self, register: int) -> int: ...
