# ruff: noqa: E402
"""MMC5603 and MMC5613 magnetometer driver."""

from dara.device.mag import Mag, MagData, MagError, mag_drivers
from dara.device.ts import TS, TSData, TSError, ts_drivers
from dara.peripheral.i2c import I2C

class MMC56X3Error(TSError, MagError):
    """Raised when an MMC56X3 operation cannot be completed."""
    ...


class MMC56X3Data(TSData, MagData):
    """Complete magnetic-field and temperature sample."""
    def __init__(self, mag: tuple[float, float, float], temperature: float) -> None:
        """Initialize a complete MMC56X3 sample."""
        ...



@mag_drivers.register("mmc56x3")
@ts_drivers.register("mmc56x3")
class MMC56X3(Mag, TS):
    """An MMC5603 or MMC5613 magnetometer connected over I2C."""
    _OUT_X = ...
    _OUT_TEMP = ...
    _ODR = ...
    _CTRL0 = ...
    _CTRL1 = ...
    _CTRL2 = ...
    _STATUS = ...
    _PRODUCT_ID = ...
    _CONTINUOUS = ...
    _HIGH_POWER = ...
    _POLL_INTERVAL = ...
    _POLL_TIMEOUT = ...
    def __init__(self, i2c: I2C, addr: int = ..., *, auto_open: bool = ...) -> None:
        """Create an MMC56X3 on a caller-owned bus and optionally initialize it."""
        ...

    def open(self) -> None:
        """Verify and initialize the sensor on its open I2C bus."""
        ...

    def close(self) -> None:
        """Disable continuous sampling without closing the caller-owned bus."""
        ...

    def __enter__(self) -> MMC56X3:
        """Open the sensor if needed and return it for a ``with`` statement."""
        ...

    def __exit__(self, *args: object) -> None:
        """Close the sensor when leaving a ``with`` statement."""
        ...

    @property
    def is_opened(self) -> bool:
        """Return whether the sensor is active on an open I2C bus."""
        ...

    def reset(self) -> None:
        """Reset the sensor, pulse its coils, and select one-shot mode."""
        ...

    def magnet_set_reset(self) -> None:
        """Pulse the sensor set and reset coils to clear magnetic offset."""
        ...

    def set_continuous_mode(self, mode: bool) -> None:
        """Enable or disable continuous magnetic sampling."""
        ...

    def is_continuous_mode(self) -> bool:
        """Return whether continuous magnetic sampling is enabled."""
        ...

    def read_temperature(self) -> float:
        """Return temperature in Celsius, or NaN during continuous sampling."""
        ...

    def set_data_rate(self, rate: int) -> None:
        """Set the output rate to 0 through 255 Hz, or high-power 1000 Hz."""
        ...

    @property
    def data_rate(self) -> int:
        """Return the cached effective output data rate in hertz."""
        ...

    def read_mag(self) -> tuple[float, float, float]:
        """Return magnetic field axes in microteslas."""
        ...

    def read_all(self) -> MMC56X3Data:
        """Return magnetic field and temperature data."""
        ...
    @property
    def _bus(self) -> I2C: ...
    def _read(self, register: int) -> int: ...
    def _write(self, register: int, value: int) -> None: ...
    def _wait_ready(self, mask: int, operation: str) -> None: ...
