# ruff: noqa: E402
"""QMI8658 six-axis inertial measurement unit driver."""

from dara.device.imu import IMU, IMUAccOdr, IMUAccScale, IMUData, IMUError, IMUGyroOdr, IMUGyroScale, IMUMode, imu_drivers
from dara.device.ts import TS, TSData, TSError, ts_drivers
from dara.peripheral.i2c import I2C

class QMI8658Error(TSError, IMUError):
    """Raised when a QMI8658 operation cannot be completed."""
    ...


class QMI8658Data(TSData, IMUData):
    """Complete accelerometer, gyroscope, and temperature sample."""
    def __init__(self, acc: tuple[float, float, float], gyro: tuple[float, float, float], temperature: float) -> None:
        """Initialize a complete QMI8658 sample."""
        ...



@imu_drivers.register("qmi8658")
@ts_drivers.register("qmi8658")
class QMI8658(IMU, TS):
    """A QMI8658 accelerometer and gyroscope connected over I2C."""
    _WHO_AM_I = ...
    _CTRL1 = ...
    _CTRL2 = ...
    _CTRL3 = ...
    _CTRL7 = ...
    _DATA = ...
    _RESET = ...
    _DEVICE_ID = ...
    _ACC_ODR = ...
    _ACC_SCALE = ...
    _GYRO_SCALE = ...
    _GYRO_ODR = ...
    def __init__(self, i2c: I2C, addr: int = ..., mode: IMUMode = ..., acc_scale: IMUAccScale = ..., acc_odr: IMUAccOdr = ..., gyro_scale: IMUGyroScale = ..., gyro_odr: IMUGyroOdr = ..., *, auto_open: bool = ...) -> None:
        """Create a QMI8658 on a caller-owned bus and optionally initialize it."""
        ...

    def open(self) -> None:
        """Reset, verify, and configure the sensor on its open I2C bus."""
        ...

    def close(self) -> None:
        """Disable sensor outputs without closing the caller-owned I2C bus."""
        ...

    def __enter__(self) -> QMI8658:
        """Open the sensor if needed and return it for a ``with`` statement."""
        ...

    def __exit__(self, *args: object) -> None:
        """Close the sensor when leaving a ``with`` statement."""
        ...

    @property
    def is_opened(self) -> bool:
        """Return whether the sensor is active on an open I2C bus."""
        ...

    def read_raw(self) -> list[float]:
        """Return uncalibrated axes followed by temperature in Celsius."""
        ...

    def read_imu(self, calib_gyro: bool = ..., radian: bool = ...) -> IMUData:
        """Return acceleration and optional calibrated or converted gyro data."""
        ...

    def read_temperature(self) -> float:
        """Return the temperature in degrees Celsius."""
        ...

    def read_all(self, calib_gyro: bool = ..., radian: bool = ...) -> QMI8658Data:
        """Return acceleration, gyro, and temperature data."""
        ...
    @property
    def _bus(self) -> I2C: ...
    def _read(self, register: int) -> int: ...
    def _write(self, register: int, value: int) -> None: ...
    def _update(self, register: int, mask: int, value: int) -> None: ...
