# ruff: noqa: E402
"""VL53L0X time-of-flight distance sensor driver.

Copyright (c) 2017-2022 Pololu Corporation.
Copyright (c) 2016 STMicroelectronics International N.V. All rights reserved.

This module derives its initialization and ranging algorithms from Pololu's
VL53L0X Arduino library and the ST VL53L0X API. The applicable license notices
are retained in the repository's ``THIRD_PARTY_LICENSES`` file.
"""

from collections.abc import Callable
from enum import Enum
from dara.device.ds import DS, DSData, DSError, ds_drivers
from dara.peripheral.i2c import I2C

class VL53L0XError(DSError):
    """Raised when a VL53L0X operation cannot be completed."""
    ...


class VL53L0XData(DSData):
    """Distance from one VL53L0X sample."""
    ...


class VL53L0XVcselPeriodType(str, Enum):
    """Ranging sequence step whose laser pulse period is configured."""
    PRE_RANGE = ...
    FINAL_RANGE = ...


class _SequenceEnables:
    """Enabled ranging sequence steps."""
    tcc: bool
    dss: bool
    msrc: bool
    pre_range: bool
    final_range: bool
    def __init__(self, tcc: bool, dss: bool, msrc: bool, pre_range: bool, final_range: bool) -> None:
        """Initialize enabled ranging sequence steps."""
        ...



class _SequenceTimeouts:
    """Decoded ranging sequence timeouts."""
    pre_period: int
    final_period: int
    msrc_mclks: int
    pre_mclks: int
    final_mclks: int
    msrc_us: int
    pre_us: int
    final_us: int
    def __init__(self, pre_period: int, final_period: int, msrc_mclks: int, pre_mclks: int, final_mclks: int, msrc_us: int, pre_us: int, final_us: int) -> None:
        """Initialize decoded ranging sequence timeouts."""
        ...



@ds_drivers.register("vl53l0x")
class VL53L0X(DS):
    """A VL53L0X time-of-flight distance sensor connected over I2C."""
    _SYSRANGE_START = ...
    _SYSTEM_SEQUENCE_CONFIG = ...
    _SYSTEM_INTERMEASUREMENT_PERIOD = ...
    _SYSTEM_INTERRUPT_CONFIG_GPIO = ...
    _SYSTEM_INTERRUPT_CLEAR = ...
    _RESULT_INTERRUPT_STATUS = ...
    _RESULT_RANGE_STATUS = ...
    _FINAL_RATE_LIMIT = ...
    _MSRC_TIMEOUT = ...
    _PRE_VALID_PHASE_LOW = ...
    _PRE_VALID_PHASE_HIGH = ...
    _PRE_VCSEL_PERIOD = ...
    _PRE_TIMEOUT = ...
    _MSRC_CONFIG_CONTROL = ...
    _FINAL_VALID_PHASE_LOW = ...
    _FINAL_VALID_PHASE_HIGH = ...
    _FINAL_VCSEL_PERIOD = ...
    _FINAL_TIMEOUT = ...
    _GPIO_HV_MUX_ACTIVE_HIGH = ...
    _I2C_ADDRESS = ...
    _EXTSUP_HV = ...
    _MODEL_ID = ...
    _OSC_CALIBRATE_VAL = ...
    _GLOBAL_VCSEL_WIDTH = ...
    _SPAD_ENABLES = ...
    _ALGO_PHASECAL = ...
    _TUNING_SETTINGS = ...
    def __init__(self, i2c: I2C, addr: int = ..., io_2v8: bool = ..., *, timeout_ms: int = ..., auto_open: bool = ...) -> None:
        """Create a VL53L0X on a caller-owned bus and optionally initialize it."""
        ...

    def __enter__(self) -> VL53L0X:
        """Open the sensor if needed and return it for a ``with`` statement."""
        ...

    def __exit__(self, *args: object) -> None:
        """Close the sensor when leaving a ``with`` statement."""
        ...

    @property
    def addr(self) -> int:
        """Return the fixed 7-bit I2C address selected at construction."""
        ...

    def open(self) -> None:
        """Verify, initialize, tune, and calibrate the sensor."""
        ...

    def close(self) -> None:
        """Stop continuous ranging without closing the caller-owned I2C bus."""
        ...

    @property
    def is_opened(self) -> bool:
        """Return whether the sensor is active on an open I2C bus."""
        ...

    def set_timeout(self, timeout_ms: int) -> None:
        """Set the polling timeout in milliseconds; zero disables timeouts."""
        ...

    def get_timeout(self) -> int:
        """Return the polling timeout in milliseconds, or zero when disabled."""
        ...

    def set_signal_rate_limit(self, limit_mcps: float) -> None:
        """Set the final-range return signal limit in mega counts per second."""
        ...

    def get_signal_rate_limit(self) -> float:
        """Return the final-range signal limit in mega counts per second."""
        ...

    def set_measurement_timing_budget(self, budget_us: int) -> None:
        """Set the measurement timing budget in microseconds."""
        ...

    def get_measurement_timing_budget(self) -> int:
        """Return the effective measurement timing budget in microseconds."""
        ...

    def set_vcsel_pulse_period(self, period_type: VL53L0XVcselPeriodType, period_pclks: int) -> None:
        """Set a pre-range or final-range VCSEL pulse period in PCLKs."""
        ...

    def get_vcsel_pulse_period(self, period_type: VL53L0XVcselPeriodType) -> int:
        """Return a pre-range or final-range VCSEL pulse period in PCLKs."""
        ...

    def start_continuous(self, period_ms: int = ...) -> None:
        """Start back-to-back or timed continuous ranging."""
        ...

    def stop_continuous(self) -> None:
        """Stop continuous ranging and restore single-shot state."""
        ...

    def read_range_continuous(self) -> float:
        """Read the next continuous range sample in centimeters."""
        ...

    def read_range_single(self) -> float:
        """Perform one range measurement and return centimeters."""
        ...

    def read_distance(self) -> float:
        """Return the next continuous or a new single-shot distance in centimeters."""
        ...

    def read_all(self) -> VL53L0XData:
        """Return distance from one sample."""
        ...
    @property
    def _bus(self) -> I2C: ...
    def _write_integer(self, register: int, value: int, width: int) -> None: ...
    def _write_stop_variable_sequence(self, *, read: bool) -> None: ...
    def _get_spad_info(self) -> tuple[int, bool]: ...
    def _get_sequence_enables(self) -> _SequenceEnables: ...
    def _get_sequence_timeouts(self, enables: _SequenceEnables) -> _SequenceTimeouts: ...
    @staticmethod
    def _decode_timeout(value: int) -> int: ...
    @staticmethod
    def _encode_timeout(timeout_mclks: int) -> int: ...
    @staticmethod
    def _macro_period_ns(period_pclks: int) -> int: ...
    @classmethod
    def _mclks_to_us(cls, timeout_mclks: int, period_pclks: int) -> int: ...
    @classmethod
    def _us_to_mclks(cls, timeout_us: int, period_pclks: int) -> int: ...
    def _perform_single_ref_calibration(self, vhv_init: int) -> None: ...
    def _wait_for(self, predicate: Callable[[], object], operation: str) -> None: ...
    def _write_reg(self, register: int, value: int) -> None: ...
    def _write_reg16_bit(self, register: int, value: int) -> None: ...
    def _write_reg32_bit(self, register: int, value: int) -> None: ...
    def _read_reg(self, register: int) -> int: ...
    def _read_reg16_bit(self, register: int) -> int: ...
    def _read_reg32_bit(self, register: int) -> int: ...
    def _write_multi(self, register: int, data: bytes | bytearray) -> None: ...
    def _read_multi(self, register: int, count: int) -> bytes: ...
