#pragma once

#include "tdl_app/audio.hpp"
#include "tdl_app/camera.hpp"
#include "tdl_app/classifier.hpp"
#include "tdl_app/display.hpp"
#include "tdl_app/detector.hpp"
#include "tdl_app/face_attribute_classifier.hpp"
#include "tdl_app/face_detector.hpp"
#include "tdl_app/face_emotion_recognizer.hpp"
#include "tdl_app/face_recognizer.hpp"
#include "tdl_app/feature_extractor.hpp"
#include "tdl_app/frame_source.hpp"
#include "tdl_app/hand_gesture_recognizer.hpp"
#include "tdl_app/image.hpp"
#include "tdl_app/instance_segmenter.hpp"
#include "tdl_app/keypoint_detector.hpp"
#include "tdl_app/lane_detector.hpp"
#include "tdl_app/media_types.hpp"
#include "tdl_app/model_descriptor.hpp"
#include "tdl_app/multi_stage_pipeline.hpp"
#include "tdl_app/npu_asr_recognizer.hpp"
#include "tdl_app/pipeline.hpp"
#include "tdl_app/plate_recognizer.hpp"
#include "tdl_app/pose_classifier.hpp"
#include "tdl_app/semantic_segmenter.hpp"
#include "tdl_app/self_learning_classifier.hpp"
#include "tdl_app/rgb_led.hpp"
#include "tdl_app/single_object_tracker.hpp"
#include "tdl_app/speech_recognizer.hpp"
#include "tdl_app/touch_input.hpp"
#include "tdl_app/vision_task_types.hpp"
#include "tdl_app/voice_activity_detector.hpp"

// Default application-facing API:
// Camera / Pipeline / common vision tasks / frame and media primitives.
